"Acción"
##########################################
### Pulling data from origin/main
### Sun, 10 Aug 2025 17:39:20 GMT
##########################################

Commit: Create .dockerignore 
 Service ospos  Building
#0 building with "default" instance using docker driver

#1 [ospos internal] load build definition from Dockerfile
#1 transferring dockerfile: 989B done
#1 DONE 0.0s
failed to solve: dockerfile parse error on line 1: unknown instruction: services:
##########################################
### Error
### Sun, 10 Aug 2025 17:39:20 GMT
##########################################

Command failed with exit code 17: docker compose -f /etc/easypanel/projects/cani_pos/ospos/code/docker-compose.yml -f /etc/easypanel/projects/cani_pos/ospos/code/docker-compose.override.yml -p cani_pos_ospos up --build -d
